DO $$ BEGIN IF NOT EXISTS (
  SELECT
  FROM
    pg_database
  WHERE
    datname = 'smart-home-db'
) THEN CREATE DATABASE "smart-home-db";

END IF;

END $$;

CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50),
  "password" varchar(50),
  "house_id" int
);

CREATE TABLE "House" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" timestamp
);

CREATE TABLE "Light" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar(20),
  "updated_time" timestamp,
  "house_id" int
);

CREATE TABLE "Door" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar(20),
  "password" varchar(20),
  "updated_time" timestamp,
  "house_id" int
);

CREATE TABLE "Fan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "speed" varchar(20),
  "updated_time" timestamp,
  "house_id" int
);

CREATE TABLE "Relay" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar(20),
  "updated_time" timestamp,
  "house_id" int
);

CREATE TABLE "Scenario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "house_id" int,
  "value" json,
  "created_at" timestamp
);

ALTER TABLE "User" ADD FOREIGN KEY ("house_id") REFERENCES "House" ("id");

ALTER TABLE "Light" ADD FOREIGN KEY ("house_id") REFERENCES "House" ("id");

ALTER TABLE "Door" ADD FOREIGN KEY ("house_id") REFERENCES "House" ("id");

ALTER TABLE "Fan" ADD FOREIGN KEY ("house_id") REFERENCES "House" ("id");

ALTER TABLE "Relay" ADD FOREIGN KEY ("id") REFERENCES "House" ("id");

ALTER TABLE "Scenario" ADD FOREIGN KEY ("house_id") REFERENCES "House" ("id");

